### ISSUE TITLE
Image crash

### ISSUE THREAD

**Issue by mabdi** [ObjectProfile/Roassal3#142] opened 2020-03-24 13:15 UTC
Hello.

When I run the following code, the Pharo image crashes.

```
	| x tmp_hKCdDYpPcF1 tmp_LAJ4vWrZ7F1 tmp_LxPVeekafT1 tmp_qSnj2I75w32 tmp_DaltCbbLhh3 tmp_xiO6y8pJCw4 tmp_MjUthwTTE75 tmp_xDqrpevmnF1 |
	x := -10.0 to: 20.0 count: 100.
	tmp_hKCdDYpPcF1 := RSChart new.
	tmp_LxPVeekafT1 := tmp_hKCdDYpPcF1
		addPlot: (RSScatterPlot new x: x y: (x raisedTo: 3)).
	tmp_qSnj2I75w32 := tmp_hKCdDYpPcF1
		addPlot: (RSLinePlot new x: x y: (x raisedTo: 2)).
	tmp_xDqrpevmnF1 := tmp_hKCdDYpPcF1 xLog.
	tmp_DaltCbbLhh3 := tmp_hKCdDYpPcF1
		addDecoration: RSHorizontalTick new.
	tmp_xiO6y8pJCw4 := tmp_hKCdDYpPcF1 addDecoration: RSVerticalTick new.
	tmp_MjUthwTTE75 := tmp_hKCdDYpPcF1 build.
	tmp_LAJ4vWrZ7F1 := tmp_hKCdDYpPcF1 show
```

The error log: 
```
Assertion failed: (angle_max >= angle_min), function _cairo_arc_in_direction, file cairo-arc.c, line 189.

```

**Comment by akevalion** [comment] 2020-03-24 18:56
This error is related with xLog scale
without `xLog` scale.

<img src="https://user-images.githubusercontent.com/10532890/77465674-c3ea3300-6de7-11ea-9b3f-9f4a9f458c4f.png" width="400">

because the scale produces Float nan numbers

```Smalltalk
x := -10.0 to: 20.0 count: 100.
y := x raisedTo: 3.
points := x with: y collect: [ :a :b | a @ b ].
scale := TSScale log.
spoints := points collect: [ :p | (scale scale: p x)@ (scale scale: p y) ].
"{(Float nan@Float nan). (Float nan@Float nan). (Float nan@Float nan). (Float nan@Float nan). (Float...3.862998102317999). (1.294399416764968@3.8831982502949045). (1.301029995663981@3.903089986991944)}"
```
Float nan in cairo produces this crash

**Comment by mabdi** [comment] 2020-03-24 20:27
Thank you for your prompt reply and explanation.

Actually the code is generated automatically by a tool. 
I think throwing an exception would be a good idea to prevent the crash.

**Comment by bergel** [comment] 2020-03-26 14:06
@akevalion why did you close the issue? It is still there... I think that the best solution is to completely ignore the NaN and Infinite values, and _not_ oblige the user to remove them.

**Comment by akevalion** [comment] 2020-04-24 02:50
xLog and yLog now accept domains with negative, positive and zero values

**Comment by bergel** [comment] 2020-04-28 02:05
The issue is now solved. Executing the script produces:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/393742/80438869-36f93480-88d3-11ea-996d-42eb927370dd.png">
No more crashes! Yupi!

**Closed by bergel** 2020-04-28 02:05 UTC
Labels: bug
